name: gs_epocket
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cached_network_image: ^1.0.1
  camera: ^0.5.3+1
  cupertino_icons: ^0.1.2
  datetime_picker_formfield: ^0.4.2
  encrypt: ^2.0.0
  hex: ^0.1.2
  http: ^0.13.3
  image_picker: ^0.6.1+3
  firebase_core: ^0.4.0+8
  firebase_messaging: ^5.1.3
  firebase_analytics: ^5.0.0
  flare_flutter: ^1.5.5
  flutter_cache_manager: ^1.0.1
  webview_flutter: ^0.3.13
#  flutter_unity_widget: ^0.1.6+2
  sqflite: ^1.1.6+3
  random_string: ^1.1.0
  path: ^1.6.2
  path_provider: ^1.2.0
  url_launcher: ^5.1.2
  validators: ^2.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2


flutter_icons:
  image_path: "./assets/logo1024.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "./assets/logo1024.png"
  android: true
  ios: true


flutter:
  uses-material-design: true  
  assets:
    - assets/

  fonts:
  - family: Gotham
    fonts:
      - asset: fonts/Gotham-Black.ttf
      - asset: fonts/Gotham-Light.ttf
      - asset: fonts/Gotham-Medium.ttf
      - asset: fonts/Gotham-Ultra.ttf
